### ISSUE TITLE
Hosted npm repository: Endpoint /{package}/{version} does not return information about specific package version

### ISSUE THREAD

**Issue by WIStudent** [sonatype/nexus-public#224]
* What problem are you trying to solve?

I have a hosted npm pository `my-npm` and published an npm package `@foo/bar` with version `1.0.0` to it. According to the [npm registry API documentation](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackageversion) the endpoint `/{package}/{version}` should return information about that specific version, but `http://localhost:8081/repository/my-npm/@foo%2Fbar/1.0.0` returned `400 Bad Request`.

If I publish an unscoped package (e.g. `foo`), `http://localhost:8081/repository/my-npm/foo/1.0.0` does not respond with HTTP Code `400` but with `404` and body 
```json
{"success":false,"error":"Package 'foo-1.0.0' not found"}
```

* Do you have a workaround you are using at present?

No

* What feature or behavior is this required for?

GitHub's dependabot uses the `/{package}/{version}` endpoint to request specific package versions from npm registries. Without this endpoint dependabot cannot check nexus hosted npm repositories for updated packages.

* How could we solve this issue? (Not knowing is okay!)

Implement the `/{package}/{version}` endpoint and return version specific package information like npmjs.com does (e.g. https://registry.npmjs.com/semver/6.3.1)

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

I used the latest sonartype/nexus3 docker image (which should be version 3.58.1) to verify this issue.
```
docker run -d -p 8081:8081 --name nexus sonatype/nexus3
```

**Comment by nblair** [comment]
Hi @WIStudent thanks for opening an issue. Our support for NPM is geared towards supporting the NPM client, and it does not appear this API you've identified is required to support the NPM client. We'll leave this issue open to gauge interest from the community.

**Comment by KagurazakaNyaa** [comment]
However, the lack of this API will cause errors in some clients that are compatible with the official registry API. Can you reconsider adding this API to ensure compatibility with the official registry?

**Comment by doteric** [comment]
Interestingly, scoped packages do not work, while unscoped actually work fine.
For example, this returns a 400 bad gateway:
```
https://my-nexus:8443/repository/npm_pull/@yarnpkg/cli-dist/4.6.0
```

While the following (for example):
```
https://my-nexus:8443/repository/npm_pull/react/19.0.0
```
returns the correct JSON.

This is a problem when using `corepack` together with Nexus due to how corepack is done.   
Example error:
```
$ yarn install --immutable
/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21616
    throw new Error(
          ^
Error: Server answered with HTTP 400 when performing the request to https://my-nexus:8443/repository/npm_pull/@yarnpkg/cli-dist/4.6.0; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21616:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchAsJson (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21623:20)
    at async fetchTarballURLAndSignature (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21571:27)
    at async installVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21833:52)
    at async Engine.ensurePackageManager (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22310:32)
    at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22410:25)
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5)
Node.js v22.12.0
```

We're currently on nexus version `3.59.0`, maybe this issue has already been resolved in a newer version by any chance?

CC @nblair 
Any chance you could take a look on this? Would really appreciate it 🙏 
Cheers!
