### ISSUE TITLE
Docker proxy using helm 

### ISSUE THREAD

**Issue by neha-live** [sonatype/nexus-public#259]
Can we configure docker nexus proxy while installing nexus through helm charts? If yes, Could you please provide some documentation? Couldn't find anywhere.

**Comment by neha-live** [comment]
Hi nblair, I took the backup of existing nexus and trying to deploy using helm charts on different node but it is failing with below error. Please assist with this
<html>
<body>


at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1597)
--
Thu, Sep 28 2023 6:59:02 pm | at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
Thu, Sep 28 2023 6:59:02 pm | at java.lang.Thread.run(Thread.java:750)
Thu, Sep 28 2023 6:59:03 pm | 2023-09-28 08:59:03,048+0000 INFO [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Uptime: 2 minutes, 16 seconds and 284 milliseconds (nexus-oss-edition/3.42.0.01)
Thu, Sep 28 2023 6:59:03 pm | 2023-09-28 08:59:03,049+0000 INFO [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Shutting down
Thu, Sep 28 2023 6:59:03 pm | 2023-09-28 08:59:03,054+0000 INFO [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Stop SECURITY
Thu, Sep 28 2023 6:59:03 pm | 2023-09-28 08:59:03,058+0000 INFO [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Stop EVENTS
Thu, Sep 28 2023 6:59:03 pm | 2023-09-28 08:59:03,058+0000 INFO [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusLifecycleManager - Stop SCHEMAS


</body>
</html>

**Comment by nblair** [comment]
Thanks for opening an issue @neha-live. To answer your first question, a common use case for our REST API is to make calls to create blobstores/repositories and most configuration options using various flavors of Infrastructure as Code tools like terraform. You'll have to sort out how to get credentials for that tool to invoke the REST API.

For your second question, that sounds like a separate concern. There's not enough detail in the sample log for us to understand what's going wrong.
