### ISSUE TITLE
[3.62.0] Downloads of large files from raw repository and Docker images from hosted docker repo backed by S3 fails with EofException on AWS ELB Classic

### ISSUE THREAD

**Issue by ju2wheels** [sonatype/nexus-public#293]
* What problem are you trying to solve?

Downloading a large 5GB ISO file from raw repository is failing and needs to be resumed multiple times to complete a download.

* Do you have a workaround you are using at present?

Just keep resuming the download until it finishes.

* What feature or behavior is this required for?

Downloading a file from the raw repository backed by S3.

* How could we solve this issue? (Not knowing is okay!)

Resolve the following exception:

```
2023-11-22 18:46:35,754+0000 WARN  [qtp2095466158-1791]  admin org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/tvision-internal-binary-test/tvision-device-ubuntu-18.04-ansible-2.6.0-qa-933f531-clonezilla-4.6.0.iso
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:280)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:378)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:119)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:300)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:503)
	at java.nio.channels.SocketChannel.write(SocketChannel.java:502)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:274)
	... 11 common frames omitted
```

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

docker-nexus3 image for 3.62.0-01 using the default internal Orient db I think, single instance running on EC2 w/Docker and ELB.

This has been a on/off again issue across multiple Nexus releases for us over the past year or two.

[Edit 2] This seems to be more wide spread than just the raw repository. Im getting the same exceptions even when downloading Docker images from a hosted Docker repo. Im guessing this is a bug in the S3 reader? I can successfully upload Docker images with 1GB image layers and a 5GB iso to the raw repo but downloading is a where I keep hitting this exception. The system resources are not anywhere near full capacity, probably around 15-20% of available capacity.

**Comment by ju2wheels** [comment]
It looks like this is an ELB issue not S3 issue, updating the title. I migrated my instance from EC2 w/ ELB Classic to ECS with ALB (application load balancer) with equivalent config using the sticky cookie NXSESSIONID and it seems to have resolved the download issues.
