### ISSUE TITLE
NullPointerException on "Publish Maven Indexer files" task

### ISSUE THREAD

**Issue by jdelker** [sonatype/nexus-public#302]
Environment:
- Sonatype Nexus Repository OSS 3.62.0-01
- AlmaLinux release 8.9
- JDK 1.8.0.392

A created task for the "Publish Maven Indexer files" task constantly fails with an NPE (see below).
The stack-trace indicates, that there is some problem with a date(format), but I've no clue where to look for.

```
Task Name: Generate Maven Indexes
Stack-trace:
org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to run task 'Publish Maven indexes of *'; 1 failure
	at org.sonatype.goodies.common.MultipleFailures.maybePropagate(MultipleFailures.java:95)
	at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:97)
	at org.sonatype.nexus.scheduling.TaskSupport.call(TaskSupport.java:100)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.doExecute(QuartzTaskJob.java:143)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.execute(QuartzTaskJob.java:106)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.sonatype.nexus.quartz.internal.QuartzThreadPool.lambda$0(QuartzThreadPool.java:145)
	at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: java.lang.NullPointerException
		at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1439)
		at java.text.DateFormat.parse(DateFormat.java:364)
		at org.apache.maven.index.reader.IndexReader.<init>(IndexReader.java:98)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.lastPublished(MavenIndexPublisher.java:207)
		at org.sonatype.nexus.repository.maven.internal.orient.OrientMavenIndexFacetSupport.lastPublished(OrientMavenIndexFacetSupport.java:46)
		at org.sonatype.nexus.repository.maven.internal.MavenIndexPublisher.publishGroupIndex(MavenIndexPublisher.java:137)
		at org.sonatype.nexus.repository.maven.internal.orient.OrientMavenGroupIndexFacet.publishIndex(OrientMavenGroupIndexFacet.java:58)
		at org.sonatype.nexus.repository.maven.tasks.PublishMavenIndexTask.execute(PublishMavenIndexTask.java:37)
		at org.sonatype.nexus.repository.RepositoryTaskSupport.execute(RepositoryTaskSupport.java:86)
		... 13 more
```

**Comment by jdelker** [comment]
Maybe worth noting:
This deployment of Nexus Repository is already several years old and was updated frequently.
That particular task was created back in 2019 and failed - unfortunately unnoticed - since then.

My guess: There is some old or missing information somewhere regarding the index, which the task is not prepared for.

**Comment by jdelker** [comment]
Found the cause when debugging:

The NPE is thrown, because the `indexReader` expects a `nexus.index.timestamp` property, which is null here.
A dive into the `remoteIndexProperties` at that point, showed, that it contained a property "nexus.index.time", rather than the above.

Obviously that originated from the configured "maven-mit-public" repository. A proxy to http://maven.mit.edu/nexus/content/repositories/public/.
As that seems down/obsolete anyway, I mitigated the problem now by removing the repository altogether.
The index task worked ok after that.

I would still consider this a bug, as code shall never encounter a uncatched NPE.

**Comment by nblair** [comment]
Thanks for the deep inspection @jdelker. The IndexReader class you mention producing the NPE is a part of an external project that's a dependency of ours: https://central.sonatype.com/artifact/org.apache.maven.indexer/indexer-reader.

I see there is a more recent version of the maven indexer-reader dependency than we are currently including, I'll surface it with the team for our tech roadmap backlog. Given that the stated repository that produces the behavior is offline, I'll consider this issue closed for now.
