### ISSUE TITLE
npm group repository search error

### ISSUE THREAD

**Issue by wzqiang1332** [sonatype/nexus-public#303]
- version: 3.62.0-01
- system: CentOS7.9

Use the npm proxy repository query "http://172.17.0.99:8081/repository/proxy-npm/@types/minimist" is normal, 
But to use npm- group aggregation repository query  "http://172.17.0.99:8081/repository/group-npm/@types/minimist" is error

The correct return value should be a JSON data
![image](https://github.com/sonatype/nexus-public/assets/20432873/5b4d1a90-33f3-4145-ad98-c9ba29ad721f)

error log
```
2023-12-12 18:09:08,608+0800 ERROR [qtp141260307-32880]  admin com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupDataFacet - Unable to use Cooperation to merge @types/minimist for repository group-npm
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (BufferedInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:750)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:728)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2541)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:701)
        at org.sonatype.nexus.repository.json.JsonParserDecorator.nextToken(JsonParserDecorator.java:211)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4912)
        at org.sonatype.nexus.repository.json.MergeObjectMapper$CustomerMergeObjectMapper.merge(MergeObjectMapper.java:159)
        at org.sonatype.nexus.repository.json.MergeObjectMapper$CustomerMergeObjectMapper.access$3(MergeObjectMapper.java:152)
        at org.sonatype.nexus.repository.json.MergeObjectMapper.merge(MergeObjectMapper.java:114)
        at com.sonatype.nexus.repository.npm.internal.NpmMergeObjectMapper.merge(NpmMergeObjectMapper.java:83)
        at com.sonatype.nexus.repository.npm.internal.NpmMergeObjectMapper.merge(NpmMergeObjectMapper.java:52)
        at com.sonatype.nexus.repository.npm.internal.NpmMetadataUtils.mergeContents(NpmMetadataUtils.java:275)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupDataFacet.buildMergedPackageRoot(OrientNpmGroupDataFacet.java:255)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupDataFacet.lambda$0(OrientNpmGroupDataFacet.java:176)
        at org.sonatype.nexus.common.io.CooperatingFuture.performCall(CooperatingFuture.java:123)
        at org.sonatype.nexus.common.io.CooperatingFuture.call(CooperatingFuture.java:65)
        at org.sonatype.nexus.common.io.ScopedCooperationFactorySupport$ScopedCooperation.cooperate(ScopedCooperationFactorySupport.java:99)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupDataFacet.buildPackageRoot(OrientNpmGroupDataFacet.java:166)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupDataFacet$buildPackageRoot$1.call(Unknown Source)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupPackageHandler.buildMergedPackageRoot(OrientNpmGroupPackageHandler.groovy:69)
        at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupPackageHandler.doGet(OrientNpmGroupPackageHandler.groovy:49)
        at org.sonatype.nexus.repository.group.GroupHandler.handle(GroupHandler.java:100)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.storage.LastDownloadedHandler.handle(LastDownloadedHandler.java:59)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.view.handlers.ContentHeadersHandler.handle(ContentHeadersHandler.java:46)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.view.handlers.ConditionalRequestHandler.handle(ConditionalRequestHandler.java:67)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.storage.UnitOfWorkHandler.handle(UnitOfWorkHandler.java:39)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.security.SecurityHandler.handle(SecurityHandler.java:51)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at com.sonatype.analytics.internal.handler.AnalyticsMeteringHandler.handle(AnalyticsMeteringHandler.java:69)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.view.handlers.TimingHandler.handle(TimingHandler.java:58)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)


2023-12-12 18:09:08,610+0800 WARN  [qtp141260307-32880]  admin org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/group-npm/%40types/minimist
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
        at com.sonatype.nexus.repository.npm.internal.NpmResponses.ok(NpmResponses.java:63)
        at com.sonatype.nexus.repository.npm.internal.NpmResponses$ok.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at com.sonatype.nexus.repository.npm.internal.NpmResponses$ok.callStatic(Unknown Source)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupPackageHandler.buildMergedPackageRoot(OrientNpmGroupPackageHandler.groovy:69)
        at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at com.sonatype.nexus.repository.npm.internal.orient.OrientNpmGroupPackageHandler.doGet(OrientNpmGroupPackageHandler.groovy:49)
        at org.sonatype.nexus.repository.group.GroupHandler.handle(GroupHandler.java:100)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.storage.LastDownloadedHandler.handle(LastDownloadedHandler.java:59)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.view.handlers.ContentHeadersHandler.handle(ContentHeadersHandler.java:46)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.view.handlers.ConditionalRequestHandler.handle(ConditionalRequestHandler.java:67)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.storage.UnitOfWorkHandler.handle(UnitOfWorkHandler.java:39)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.security.SecurityHandler.handle(SecurityHandler.java:51)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at com.sonatype.analytics.internal.handler.AnalyticsMeteringHandler.handle(AnalyticsMeteringHandler.java:69)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.view.handlers.TimingHandler.handle(TimingHandler.java:58)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:88)
        at org.sonatype.nexus.repository.view.Context.start(Context.java:179)
        at org.sonatype.nexus.repository.view.Router.dispatch(Router.java:65)
        at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:52)
        at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:43)
        at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.dispatchAndSend(ViewServlet.java:212)
        at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.doService(ViewServlet.java:174)
        at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.service(ViewServlet.java:126)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:293)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:283)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.DynamicServletPipeline.service(DynamicServletPipeline.java:71)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
```

**Comment by nblair** [comment]
Hi @wzqiang1332 thanks for opening an issue. I'm unable to replicate the error you are reporting here with a proxy repository and a group repository containing the proxy; I get a successful JSON response from both. Can you provide more details about what repositories your group is composed of?

**Comment by wzqiang1332** [comment]
> Hi @wzqiang1332 thanks for opening an issue. I'm unable to replicate the error you are reporting here with a proxy repository and a group repository containing the proxy; I get a successful JSON response from both. Can you provide more details about what repositories your group is composed of?

When "https://registry.npm.taobao.org" proxy is added to the group, visit the component url will result in an error , the actual package in "https://registry.npmjs.org" proxy

**Comment by wzqiang1332** [comment]
Remove the old group and add a new group. It is all right now
