### ISSUE TITLE
 ERROR [FelixStartLevel]  *SYSTEM org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Failed transition: NEW -> STARTED

### ISSUE THREAD

**Issue by Yang000111** [sonatype/nexus-public#321]
upgade version to nexus-3.64.0-04,  i have a error as follows:

2024-01-16 20:41:31,967+0800 ERROR [FelixStartLevel]  *SYSTEM org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Failed transition: NEW -> STARTED
java.lang.IllegalStateException: Missing recipe: apk-proxy
        at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
        at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.recipe(RepositoryManagerImpl.java:159)
        at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.newRepository(RepositoryManagerImpl.java:177)
        at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.restoreRepositories(RepositoryManagerImpl.java:274)
        at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.doStart(RepositoryManagerImpl.java:256)
        at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69)
        at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
        at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:206)
        at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:57)
        at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:199)
        at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:111)
        at org.sonatype.nexus.extender.NexusContextListener.moveToPhase(NexusContextListener.java:319)
        at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:216)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1597)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:750)

i did`not how to recover my nexus,  help me please

**Comment by mrprescott** [comment]
@Yang000111 It looks like you might have a missing plugin, and/or a problem loading the APK plugin. My understanding is the APK plugin may be considerably behind in terms of compatibility with recent versions of Nexus Repository, it's possible that's the cause here.

**Comment by Yang000111** [comment]
What is the apk plugin used for? How do I install or uninstall plug-ins

**Comment by Yang000111** [comment]
Thanks for your reminding, I successfully solved the problem,I'm missing the nexus-repository-apk-0.0.26-bundle.kar plugin
