### ISSUE TITLE
Nexus throwing EventDispatcher: Error during dispatch. (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by xujiajie-jiangnan** [sonatype/nexus-public#377]
When I ported and adapted Nexus-3.60 to a certain architecture chip and ran Nexus-3.60 without using the adapted zstd-jni-1.4.8-7.jar, the following issues occurred:

```
2024-04-09 14:29:05,387+0800 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - ACTIVATING org.sonatype.nexus.plugins.nexus-repository-apt [3.60.0.02]
2024-04-09 14:29:05,728+0800 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - ACTIVATED org.sonatype.nexus.plugins.nexus-repository-apt [3.60.0.02]
2024-04-09 14:29:05,744+0800 ERROR [FelixDispatchQueue]  *SYSTEM Events.Framework - FrameworkEvent ERROR
org.osgi.framework.BundleException: Unable to resolve com.github.luben.zstd-jni [248](R 248.0): missing requirement [com.github.luben.zstd-jni [248](R 248.0)] osgi.native; (|(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc64))(&(|(osgi.native.osname~=macos)(osgi.native.osname~=macosx))(osgi.native.processor~=x86_64))(&(|(osgi.native.osname~=macos)(osgi.native.osname~=macosx))(osgi.native.processor~=aarch64))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=amd64))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=i386))(&(osgi.native.osname~=linux)(osgi.native.processor~=aarch64))(&(osgi.native.osname~=linux)(osgi.native.processor~=amd64))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm))(&(osgi.native.osname~=linux)(osgi.native.processor~=i386))(&(osgi.native.osname~=linux)(osgi.native.processor~=mips64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64le))(&(osgi.native.osname~=linux)(osgi.native.processor~=s390x))(&(osgi.native.osname~=win32)(osgi.native.processor~=amd64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))) Unresolved requirements: [[com.github.luben.zstd-jni [248](R 248.0)] osgi.native; (|(&(osgi.native.osname~=aix)(osgi.native.processor~=ppc64))(&(|(osgi.native.osname~=macos)(osgi.native.osname~=macosx))(osgi.native.processor~=x86_64))(&(|(osgi.native.osname~=macos)(osgi.native.osname~=macosx))(osgi.native.processor~=aarch64))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=amd64))(&(osgi.native.osname~=freebsd)(osgi.native.processor~=i386))(&(osgi.native.osname~=linux)(osgi.native.processor~=aarch64))(&(osgi.native.osname~=linux)(osgi.native.processor~=amd64))(&(osgi.native.osname~=linux)(osgi.native.processor~=arm))(&(osgi.native.osname~=linux)(osgi.native.processor~=i386))(&(osgi.native.osname~=linux)(osgi.native.processor~=mips64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64))(&(osgi.native.osname~=linux)(osgi.native.processor~=ppc64le))(&(osgi.native.osname~=linux)(osgi.native.processor~=s390x))(&(osgi.native.osname~=win32)(osgi.native.processor~=amd64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
````

When I replaced the adapted zstd-jni-1.4.8-7.jar, the following issues occurred:

```
2024-04-09 14:35:11,124+0800 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - ACTIVATING org.sonatype.nexus.plugins.nexus-repository-apt [3.60.0.02]
2024-04-09 14:35:11,457+0800 INFO  [FelixStartLevel]  *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - ACTIVATED org.sonatype.nexus.plugins.nexus-repository-apt [3.60.0.02]
2024-04-09 14:35:11,476+0800 ERROR [FelixStartLevel]  *SYSTEM Felix - Bundle org.sonatype.nexus.extender [96] EventDispatcher: Error during dispatch. (java.lang.NullPointerException)
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.add(ConcurrentHashMap.java:4595)
        at org.sonatype.nexus.extender.NexusBundleTracker.prepare(NexusBundleTracker.java:60)
        at org.eclipse.sisu.launch.SisuTracker.addingBundle(SisuTracker.java:129)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:420)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
        at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
        at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4817)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2393)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)

```

Can these problems be attributed to zstd-jni?

**Comment by nblair** [comment]
Hi @xujiajie-jiangnan thanks for opening an issue. It's not clear here what you are attempting, it sounds like some sort of custom modification or environment that we have no familiarity with. If it's not the typical deployment of [Sonatype's distribution](https://help.sonatype.com/en/download.html) on something following our [system requirements](https://help.sonatype.com/en/sonatype-nexus-repository-system-requirements.html), we may not be able to provide any assistance.
