### ISSUE TITLE
Yum group repo returns http 500 error when inner repo uses xzst compression

### ISSUE THREAD

**Issue by seregaizsbera** [sonatype/nexus-public#392]
* What problem are you trying to solve?

Yum group repository returns http 500 error.

** Steps to reproduce

1. Create yum proxy repository with zst compressed metadata, for example, Remote storage: https://repo1.red-soft.ru/redos/8.0/x86_64/os/
2. Add proxy repository to group
3. Try to download metadata from group repository `dnf makecache`.

** Expected result

1. Metadata cached successfully

** Actual result

1. DNF writes error messages Failed to synchronize cache for repo 'test', ignoring this repo.
2. nexus.log contains the following exception:

<details><summary>XMLStreamException</summary>
<p>
<pre>
java.lang.RuntimeException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.merge(YumMetadataMerger.java:235)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.mergeStreams(YumMetadataMerger.java:171)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.mergeStreamsAndUpdate(YumMetadataMerger.java:150)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.merge(YumMetadataMerger.java:139)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMergeServiceImpl.generateMergedFile(YumMergeServiceImpl.java:78)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMergeServiceImpl.merge(YumMergeServiceImpl.java:57)
        at org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl.mergeResponses(YumGroupMergerImpl.java:121)
        at org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl.lambda$2(YumGroupMergerImpl.java:71)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl.fetchAndMergeMetadata(YumGroupMergerImpl.java:73)
        at org.sonatype.nexus.repository.yum.orient.internal.group.OrientYumGroupFacetImpl.buildRepomd(OrientYumGroupFacetImpl.java:150)
        at org.sonatype.nexus.repository.yum.internal.group.YumMergingGroupHandlerSupport.merge(YumMergingGroupHandlerSupport.java:67)
        at org.sonatype.nexus.repository.group.MergingGroupHandlerSupport.lambda$8(MergingGroupHandlerSupport.java:147)
</pre>
</p>
</details> 

* Do you have a workaround you are using at present?
No

* What feature or behavior is this required for?
Yum group repository.

* How could we solve this issue? (Not knowing is okay!)
```java
if (repomdFile.endsWith(".zst") {
    var unpackedFile = unpack(repomdFile);
    repomdFile = unpackedFile;
}
yumMetadataMerger.merge(repomdFile);
``` 
The problem looks very much like issue #338.

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
* Anything else?

Sonatype Nexus RepositoryOSS 3.68.0-04, OrientDB, Fedora 39.

**Comment by nblair** [comment]
Thanks for opening an issue @seregaizsbera . I don't think this is related to #338, which is focused on nuget support.
Are there other examples of this xzst compression used by packages in other providers, like http://mirror.centos.org/centos/?
If it's unique to that provider, it may not be something Nexus Repository has support for, and would be more akin to an enhancement request.

**Comment by seregaizsbera** [comment]
@nblair I had been observing the same in https://archives.fedoraproject.org/pub/fedora/linux/releases/40/Server/x86_64/os/repodata/. But now it looks like they switched back to good old gz compression.

**Comment by btheu** [comment]
I have same issue (with version 3.84.0).  

To reproduce, create 2 yum `proxy` repo with those 2 urls :

- https://dl.rockylinux.org/pub/rocky/9/CRB/x86_64/os/
- https://download.docker.com/linux/centos/9/x86_64/stable/

Create one `group` repo called `rocky-9-public` owning the two previous `proxy` repo.

GET http://localhost:8081/repository/rocky-9-public/repodata/repomd.xml will respond with html `500` code.

Docker yum repo for centos 9 and plus are using `zst` file format which cause `Nexus` issue when merging metadata.

**Comment by btheu** [comment]
2025-09-16 09:16:00,042+0000 INFO  [qtp1510211710-91] admin org.sonatype.nexus.repository.yum.datastore.internal.group.YumGroupFacetImpl - Creating latest metadata by merging metadata of group members for repository rocky-9-public
2025-09-16 09:16:00,119+0000 INFO  [qtp1510211710-91] admin org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl - Requesting **repodata/cdc79373d1ff13418b0895f21e0b4a55925d512c7d9626795ac30472b307bbb5-other.xml.zst** from rocky-9-docker
2025-09-16 09:16:00,159+0000 INFO  [qtp1510211710-91] admin org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl - Requesting repodata/cdb2fa29-cae6-4ae0-b51e-dcfe7c8ebb94-OTHER.xml.gz from yum-rocky-9-crb-x86-64
2025-09-16 09:16:00,354+0000 INFO  [qtp1510211710-91] admin org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl - Merge of other.xml.gz starting
2025-09-16 09:16:00,476+0000 ERROR [qtp1510211710-91] admin org.sonatype.nexus.repository.yum.internal.mergerepo.OtherMetadataMerger - Error at time to merge 2 streams for metadata files
2025-09-16 09:16:00,480+0000 WARN  [qtp1510211710-91] admin org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Failure servicing: GET /repository/rocky-9-public/repodata/repomd.xml
java.lang.RuntimeException: com.ctc.wstx.exc.WstxIOException: **Invalid UTF-8 start byte 0xb5 (at char #2, byte #-1)**
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.merge(YumMetadataMerger.java:236)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.mergeStreams(YumMetadataMerger.java:172)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.mergeStreamsAndUpdate(YumMetadataMerger.java:150)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.merge(YumMetadataMerger.java:138)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMergeServiceImpl.generateMergedFile(YumMergeServiceImpl.java:78)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMergeServiceImpl.merge(YumMergeServiceImpl.java:57)
        at org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl.mergeResponses(YumGroupMergerImpl.java:121)
        at org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl.lambda$2(YumGroupMergerImpl.java:71)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.sonatype.nexus.repository.yum.internal.group.YumGroupMergerImpl.fetchAndMergeMetadata(YumGroupMergerImpl.java:73)
        at org.sonatype.nexus.repository.yum.datastore.internal.group.YumGroupFacetImpl.buildRepomd(YumGroupFacetImpl.java:134)
        at org.sonatype.nexus.repository.yum.internal.group.YumMergingGroupHandler.merge(YumMergingGroupHandler.java:76)
        at org.sonatype.nexus.repository.group.MergingGroupHandlerSupport.lambda$7(MergingGroupHandlerSupport.java:147)
        at org.sonatype.nexus.common.cooperation2.ScopedCooperation2Support$ScopedCooperation2Builder.perform(ScopedCooperation2Support.java:86)
        at org.sonatype.nexus.common.cooperation2.datastore.internal.CooperatingFuture.performCall(CooperatingFuture.java:126)
        at org.sonatype.nexus.common.cooperation2.datastore.internal.CooperatingFuture.call(CooperatingFuture.java:68)
        at org.sonatype.nexus.common.cooperation2.ScopedCooperation2Support$ScopedCooperation2Builder.cooperate(ScopedCooperation2Support.java:103)
        at org.sonatype.nexus.repository.group.MergingGroupHandlerSupport.merge(MergingGroupHandlerSupport.java:149)
        at org.sonatype.nexus.repository.group.MergingGroupHandlerSupport.doGet(MergingGroupHandlerSupport.java:128)
        at org.sonatype.nexus.repository.group.GroupHandler.handle(GroupHandler.java:106)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.content.handlers.LastDownloadedHandler.handle(LastDownloadedHandler.java:67)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.view.handlers.ContentHeadersHandler.handle(ContentHeadersHandler.java:46)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.view.handlers.ConditionalRequestHandler.handle(ConditionalRequestHandler.java:73)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at com.sonatype.analytics.internal.handler.AnalyticsBytesTransferredHandler.handle(AnalyticsBytesTransferredHandler.java:51)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at com.sonatype.analytics.internal.handler.S3EgressContributedHandler.handle(S3EgressContributedHandler.java:65)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at com.sonatype.analytics.internal.handler.AnalyticsBytesTransferredHandler.handle(AnalyticsBytesTransferredHandler.java:51)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at com.sonatype.nexus.clm.internal.datastore.FirewallContributedHandler.handle(FirewallContributedHandler.java:123)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at com.sonatype.nexus.community.analytics.handler.ThrottlingContributedHandler.handle(ThrottlingContributedHandler.java:87)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.view.handlers.HandlerContributor.handle(HandlerContributor.java:67)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.view.handlers.ExceptionHandler.handle(ExceptionHandler.java:48)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.security.SecurityHandler.handle(SecurityHandler.java:67)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.yum.datastore.internal.YumAssetKindHandler.handle(YumAssetKindHandler.java:30)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at com.sonatype.analytics.internal.handler.AnalyticsMeteringHandler.handle(AnalyticsMeteringHandler.java:75)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.view.handlers.TimingHandler.handle(TimingHandler.java:59)
        at org.sonatype.nexus.repository.view.Context.proceed(Context.java:96)
        at org.sonatype.nexus.repository.view.Context.start(Context.java:187)
        at org.sonatype.nexus.repository.view.Router.dispatch(Router.java:65)
        at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:55)
        at org.sonatype.nexus.repository.view.ConfigurableViewFacet.dispatch(ConfigurableViewFacet.java:46)
        at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.dispatchAndSend(ViewServlet.java:214)
        at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.doService(ViewServlet.java:176)
        at org.sonatype.nexus.repository.httpbridge.internal.ViewServlet.service(ViewServlet.java:128)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.ee8.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1146)
        at org.eclipse.jetty.ee8.servlet.ServletHolder.handle(ServletHolder.java:640)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1374)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
        at org.sonatype.nexus.security.SecurityFilter.executeChain(SecurityFilter.java:91)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
        at org.sonatype.nexus.security.SecurityFilter.doFilterInternal(SecurityFilter.java:108)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at com.sonatype.analytics.internal.filter.ResponseSizeInterceptor.doFilter(ResponseSizeInterceptor.java:57)
        at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at com.sonatype.analytics.internal.filter.RealtimeThroughputMetricsFilter.doFilter(RealtimeThroughputMetricsFilter.java:69)
        at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at com.sonatype.analytics.internal.filter.ThroughputMetricsFilter.doFilter(ThroughputMetricsFilter.java:81)
        at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at org.sonatype.nexus.repository.httpbridge.internal.ExhaustRequestFilter.doFilter(ExhaustRequestFilter.java:94)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at com.sonatype.nexus.licensing.internal.LicensingRedirectFilter.doFilter(LicensingRedirectFilter.java:123)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:112)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at org.sonatype.nexus.internal.web.EnvironmentFilter.doFilter(EnvironmentFilter.java:107)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at org.sonatype.nexus.internal.web.HeaderPatternFilter.doFilter(HeaderPatternFilter.java:103)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at org.sonatype.nexus.internal.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:84)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at org.sonatype.nexus.internal.web.HttpRequestProvider.doFilter(HttpRequestProvider.java:51)
        at org.eclipse.jetty.ee8.servlet.FilterHolder.doFilter(FilterHolder.java:171)
        at org.eclipse.jetty.ee8.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1348)
        at org.eclipse.jetty.ee8.servlet.ServletHandler.doHandle(ServletHandler.java:454)
        at org.eclipse.jetty.ee8.nested.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.ee8.security.SecurityHandler.handle(SecurityHandler.java:497)
        at org.eclipse.jetty.ee8.nested.HandlerWrapper.handle(HandlerWrapper.java:108)
        at org.eclipse.jetty.ee8.nested.ScopedHandler.nextHandle(ScopedHandler.java:183)
        at org.eclipse.jetty.ee8.nested.SessionHandler.doHandle(SessionHandler.java:519)
        at org.eclipse.jetty.ee8.nested.ScopedHandler.nextHandle(ScopedHandler.java:181)
        at org.eclipse.jetty.ee8.nested.ContextHandler.doHandle(ContextHandler.java:885)
        at org.eclipse.jetty.ee8.nested.ScopedHandler.nextScope(ScopedHandler.java:152)
        at org.eclipse.jetty.ee8.servlet.ServletHandler.doScope(ServletHandler.java:423)
        at org.eclipse.jetty.ee8.nested.ScopedHandler.nextScope(ScopedHandler.java:150)
        at org.eclipse.jetty.ee8.nested.SessionHandler.doScope(SessionHandler.java:503)
        at org.eclipse.jetty.ee8.nested.ScopedHandler.nextScope(ScopedHandler.java:150)
        at org.eclipse.jetty.ee8.nested.ContextHandler.doScope(ContextHandler.java:830)
        at org.eclipse.jetty.ee8.nested.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.ee8.nested.ContextHandler.handle(ContextHandler.java:1443)
        at org.eclipse.jetty.ee8.nested.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1291)
        at org.eclipse.jetty.ee8.nested.HttpChannel.dispatch(HttpChannel.java:617)
        at org.eclipse.jetty.ee8.nested.HttpChannel.handle(HttpChannel.java:459)
        at org.eclipse.jetty.ee8.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2450)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1064)
        at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
        at io.dropwizard.metrics.jetty12.AbstractInstrumentedHandler.handle(AbstractInstrumentedHandler.java:299)
        at org.sonatype.nexus.repository.docker.internal.DockerRequestHandler.handle(DockerRequestHandler.java:43)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
        at org.eclipse.jetty.server.Server.handle(Server.java:182)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:678)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:416)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:443)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Thread.java:840)
**Caused by: com.ctc.wstx.exc.WstxIOException: Invalid UTF-8 start byte 0xb5 (at char #2, byte #-1)**
        at com.ctc.wstx.sr.StreamScanner.constructFromIOE(StreamScanner.java:653)
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1017)
        at com.ctc.wstx.sr.StreamScanner.getNext(StreamScanner.java:770)
        at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2096)
        at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180)
        at com.ctc.wstx.evt.WstxEventReader.nextEvent(WstxEventReader.java:283)
        at org.sonatype.nexus.repository.yum.internal.mergerepo.YumMetadataMerger.merge(YumMetadataMerger.java:216)
        ... 168 common frames omitted
**Caused by: java.io.CharConversionException: Invalid UTF-8 start byte 0xb5 (at char #2, byte #-1)**
        at com.ctc.wstx.io.UTF8Reader.reportInvalidInitial(UTF8Reader.java:307)
        at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:192)
        at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:88)
        at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:57)
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1011)
        ... 173 common frames omitted
