### ISSUE TITLE
Uploading asc files to YUM repositories no longer possible

### ISSUE THREAD

**Issue by jeanmichelfischer** [sonatype/nexus-public#402]
We would like to sign hosted YUM repositories, as described for example for the YUM proxy repositories in the documentation. 

To do this, we uploaded the repomd.xml.asc files (manually/via the API). However, in the latest versions of Nexus3 it is no longer possible to upload .asc files. 

This means that signing is no longer possible. Is there a solution to this, or are we missing something?

The error message, if you try to upload asc-files,  is: 
_Unsupported assetKind: REPOMD_ASC_

![Screenshot](https://github.com/sonatype/nexus-public/assets/8353169/be2f0822-e9ea-4026-bc3b-616c86bca7ff)

**Comment by nblair** [comment]
Hi @jeanmichelfischer - thanks for opening an issue. Can you provide some more detail about which version you used when this type of asset was supported?

**Comment by jeanmichelfischer** [comment]
Hi @nblair - I can only track it down to it was working at _Version OSS 3.29.0-02_ and not working from _Version OSS 3.49.0-02_ anymore. This might not be the exact Versions when it stopped working, but it might be a hint.

**Comment by jeanmichelfischer** [comment]
Here is a Log snippet:

`2024-05-31 18:57:04,462+0000 INFO  [qtp1877013011-4897]  restapi org.sonatype.nexus.repository.upload.internal.OrientUploadManagerImpl - Uploading component with parameters: repository="x_internal_test" format="yum" directory="/repodata" 
2024-05-31 18:57:04,463+0000 INFO  [qtp1877013011-4897]  restapi org.sonatype.nexus.repository.upload.internal.OrientUploadManagerImpl - Asset with parameters: file="repomd.xml.asc" filename="repomd.xml.asc" 
2024-05-31 18:57:04,475+0000 WARN  [qtp1877013011-4897]  restapi org.sonatype.nexus.siesta.internal.UnexpectedExceptionMapper - (ID f866d49e-40f9-4c0a-9751-a93d78b090ba) Unexpected exception: java.lang.IllegalArgumentException: Unsupported assetKind: REPOMD_ASC
java.lang.IllegalArgumentException: Unsupported assetKind: REPOMD_ASC
	at org.sonatype.nexus.repository.yum.orient.internal.hosted.OrientYumHostedFacetImpl.upload(OrientYumHostedFacetImpl.java:128)
	at org.sonatype.nexus.repository.yum.orient.internal.upload.OrientYumUploadHandler.handle(OrientYumUploadHandler.java:103)
	at org.sonatype.nexus.repository.upload.internal.OrientUploadManagerImpl.handle(OrientUploadManagerImpl.java:110)
	at org.sonatype.nexus.repository.rest.internal.resources.ComponentsResource.uploadComponent(ComponentsResource.java:260)`

**Comment by gfelot** [comment]
Hi !
Same issue with a brand new install of the last version `nexus-3.69.0-02-java11-unix`.
Anyone on this issue ?
