### ISSUE TITLE
In sonatype/nexus3:3.69.0-java17 got The maximum Java version for OrientDb is Java 11. Please check current Java version meets this requirement.

### ISSUE THREAD

**Issue by kappa8219** [sonatype/nexus-public#419]
### After upgrade to sonatype/nexus3:3.69.0-java17 from sonatype/nexus3:3.68.1-java11 got such an exception on container start:

`2024-07-02 06:14:21,036+0000 ERROR [jetty-main-1] *SYSTEM org.sonatype.nexus.bootstrap.osgi.BootstrapListener - Failed to initialize
java.lang.IllegalStateException: The maximum Java version for OrientDb is Java 11. Please check current Java version meets this requirement.
	at org.sonatype.nexus.bootstrap.osgi.NexusEditionPropertiesConfigurer.ensureOrientRunningWithCorrectJavaRuntime(NexusEditionPropertiesConfigurer.java:149)
	at org.sonatype.nexus.bootstrap.osgi.NexusEditionPropertiesConfigurer.selectDbFeature(NexusEditionPropertiesConfigurer.java:138)
	at org.sonatype.nexus.bootstrap.osgi.NexusEditionPropertiesConfigurer.selectDatastoreFeature(NexusEditionPropertiesConfigurer.java:127)
	at org.sonatype.nexus.bootstrap.osgi.NexusEditionPropertiesConfigurer.getPropertiesFromConfiguration(NexusEditionPropertiesConfigurer.java:58)
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:58)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1073)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:1002)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:765)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
`

Runtime is AWS EKS 1.30. Details:

OS linux (amd64)

OS Image Amazon Linux 2023.4.20240528

Kernel version 6.1.91-99.172.amzn2023.x86_64

Container runtime containerd://1.7.11

Kubelet version v1.30.0-eks-036c24b

#### sonatype/nexus3:3.69.0-java11 started successfully. So image with Java17 does not work.

**Comment by nblair** [comment]
The release notes state that Java 17 support is for Deployments Using H2 or PostgreSQL Databases, both which require a Pro license.

https://help.sonatype.com/en/sonatype-nexus-repository-3-69-0-release-notes.html

**Comment by kappa8219** [comment]
Indeed, just read it in Release Notes. Sorry for bothering.
