### ISSUE TITLE
Realms not shown in UI (3.70.1-02)

### ISSUE THREAD

**Issue by rmontag-ap** [sonatype/nexus-public#444]
Nexus OSS 3.70.1-02
When clicking on Administration -> Security -> Realms, I got an empty page and nothing is shown.
Enabling the Developer Tool in Chrome shows the following errors:

![image](https://github.com/user-attachments/assets/c8ddf52a-2bc6-4085-9eaf-520af7a7d8e4)

```
nexus-coreui-plugin-prod.js?_v=3.70.1-02&_e=OSS&_c=2024-07-11-0055-20393:1
TypeError: Cannot read properties of undefined (reading 'id')
    at NxTransferListHalf.js:87:318
    at Array.map (<anonymous>)
    at MC (NxTransferListHalf.js:87:158)
    at ii (react-dom.production.min.js:157:137)
    at Xc (react-dom.production.min.js:267:460)
    at kl (react-dom.production.min.js:250:347)
    at Nl (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
...
    
NxTransferListHalf.js:87
Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'id')
    at NxTransferListHalf.js:87:318
    at Array.map (<anonymous>)
    at MC (NxTransferListHalf.js:87:158)
    at ii (react-dom.production.min.js:157:137)
    at Xc (react-dom.production.min.js:267:460)
    at kl (react-dom.production.min.js:250:347)
    at Nl (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
```

Tested with Chrome 127.0.6533.99 and Firefox 115.13.0esr 
I cannot tell if this is a new problem with the version 3.70.1 or not.

**Comment by rmontag-ap** [comment]
Still have this issue in 3.70.2-01.

Is it only me having the issue? Can someone confirm if this problem exists?

**Comment by rmontag-ap** [comment]
And the same on 3.70.3-01.

**Comment by tklein** [comment]
Although it's already quite a while ago I was able to solve that for my instance.

Same situation here and I then figured out that I had used a custom realm plugin that is no longer working. This caused the issue.

To sort that out I used the REST-API.

To get the list of configured realms

```
curl -u admin:YOUR_PASSWORD \
  -X GET "http://<nexus-host>:8081/service/rest/v1/security/realms/active" \
  -H "Accept: application/json"
```

and to update one can use

```
curl -u admin:YOUR_PASSWORD \
  -X PUT "http://<nexus-host>:8081/service/rest/v1/security/realms/active" \
  -H "Content-Type: application/json" \
  -d '[
    "NexusAuthenticatingRealm",
    "NexusAuthorizingRealm",
    "DockerToken"
  ]'
```

Just in case someone stumble accross this problem.

**Comment by rmontag-ap** [comment]
I totally forgot about this issue ;-)

I have checked with my current 3.87.1-01 and the realms are shown in the UI.
I checked my active realms:
`[ "User-Token-Realm", "NexusAuthenticatingRealm", "LdapRealm", "DockerToken", "NpmToken", "NuGetApiKey" ]`

So I will close this issue.
