### ISSUE TITLE
The database duplicates its size when yum rebuild metadata task is run

### ISSUE THREAD

**Issue by yasser583** [sonatype/nexus-public#473]
As I try to rebuild the metadata for a yum repository using the provided task, the db size duplicates, it went from some gigabytes and now is on about 200.
Please your help.

**Comment by yasser583** [comment]
I see this error in the logs:

```
2024-09-08 14:06:55,708-0400 WARN  [quartz-9-thread-19]  *SYSTEM org.sonatype.nexus.quartz.internal.task.QuartzTaskJob - Task e727a802-a0cb-4352-a0bf-1d7710ddf07c : 'Metadata rebuild for centos-nonprod for /centos/7/os/x86_64/' [automatic.yum.metadata.rebuild] execution failure
java.lang.NullPointerException: Cannot invoke "org.quartz.JobDetail.getKey()" because "jobDetail" is null
	at org.sonatype.nexus.quartz.internal.datastore.DatastoreQuartzSchedulerSPI.attachJobListener(DatastoreQuartzSchedulerSPI.java:147)
	at org.sonatype.nexus.quartz.internal.datastore.DatastoreQuartzSchedulerSPI.attachJobListener(DatastoreQuartzSchedulerSPI.java:128)
	at org.sonatype.nexus.quartz.internal.datastore.DatastoreQuartzSchedulerSPI.getOrCreateQuartzTaskInfo(DatastoreQuartzSchedulerSPI.java:175)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.sonatype.nexus.quartz.internal.datastore.DatastoreQuartzSchedulerSPI.allTasks(DatastoreQuartzSchedulerSPI.java:164)
	at org.sonatype.nexus.quartz.internal.QuartzSchedulerSPI.listsTasks(QuartzSchedulerSPI.java:571)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:287)
	at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:54)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.blockedBy(QuartzTaskJob.java:264)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.mayBlock(QuartzTaskJob.java:200)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.doExecute(QuartzTaskJob.java:139)
	at org.sonatype.nexus.quartz.internal.task.QuartzTaskJob.execute(QuartzTaskJob.java:106)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.sonatype.nexus.quartz.internal.QuartzThreadPool.lambda$0(QuartzThreadPool.java:145)
	at org.sonatype.nexus.thread.internal.MDCAwareRunnable.run(MDCAwareRunnable.java:40)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by yasser583** [comment]
Also, when there's an error, the rebuild metadata task vanishes from the tasks list.
I'm using Nexus version 3.71.0-06.
Thank you.
