### ISSUE TITLE
Help needed : Invalid keystore password (used to work)

### ISSUE THREAD

**Issue by jeanfrancoisgratton** [sonatype/nexus-public#489]
My NAS' motherboard broke so I now have to rebuild from scratch my Nexus docker container.

Before I forget : I am running Nexus OSS v3.73.0-12 . The files and configs mentioned below used to work on v3.69.0
The nexus app is in /opt/nexus3/nexus, the data dir is /opt/nexus3/sonatype-work/nexus/

As I need https communications, I have the following files:
**/opt/nexus3/sonatype-work/nexus/etc/nexus.properties** :
```
# Jetty section
nexus-args=${jetty.etc}/jetty.xml,${jetty.etc}/jetty-https.xml,${jetty.etc}/jetty-requestlog.xml

application-port-ssl=18089
ssl.etc=${karaf.data}/etc/ssl
```

**/opt/nexus3/sonatype-work/nexus/etc/jetty/jetty-https.xml** :
(relevant section)
  ```
<New id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory$Server">
    <Set name="KeyStorePath"><Property name="ssl.etc"/>/keystore.jks</Set>
    <Set name="KeyStorePassword">MYPASSWORD</Set>
    <Set name="KeyManagerPassword">MYPASSWORD</Set>
    <Set name="TrustStorePath"><Property name="ssl.etc"/>/keystore.jks</Set>
    <Set name="TrustStorePassword">MYPASSWORD</Set>
    <Set name="EndpointIdentificationAlgorithm"></Set>
    <Set name="NeedClientAuth"><Property name="jetty.ssl.needClientAuth" default="false"/></Set>
    <Set name="WantClientAuth"><Property name="jetty.ssl.wantClientAuth" default="false"/></Set>
    <Set name="IncludeProtocols">
      <Array type="java.lang.String">
        <Item>TLSv1.2</Item>
      </Array>
    </Set>
  </New>
```

The keystore, `/opt/nexus3/sonatype-work/nexus3/etc/ssl/keystore.jks` does have the correct password, as tested with keytool:
```
[15:16:59|nexus@nexus:~/sonatype-work/nexus3/etc/ssl] keytool -list -keystore keystore.jks
Enter keystore password:
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

1, Jul 9, 2024, PrivateKeyEntry,
Certificate fingerprint (SHA-256): 0E:C4:9D:E8:9C:24:5B:C8:61:67:93:93:F7:2C:AA:6A:7E:7A:CE:9F:87:C8:CB:BD:43:5E:FE:74:44:70:D5:E7

```

Yet, Nexus fails to start, complaining of a wrong password:

```
2024-10-14 14:59:56,683-0400 ERROR [jetty-main-1]  *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Failed to start
java.io.IOException: keystore password was incorrect
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2159)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:242)
        at java.base/java.security.KeyStore.load(KeyStore.java:1473)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1203)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:322)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:244)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:323)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:274)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
```

The keystore file is owned by nexus:nexus, with 0644 perms. Actually, the whole /opt/nexus3 directory is owned by nexus:nexus.

Is there something I might be missing ?

**Comment by jeanfrancoisgratton** [comment]
Fixed.. I will review the documentation more carefully, but I _think_ I might have read that jett-https.xml should be in $data-dir/etc/jetty/ and also read that it should be in $install-dir/etc/jetty (conflicting doc ?). Unsure.

Bottom line, the correct destination is $install-dir/etc/jetty/
