### ISSUE TITLE
Error after upgrade to 3.74 with S3  based blob store

### ISSUE THREAD

**Issue by anuragpathak21** [sonatype/nexus-public#532]
I have upgraded to 3.74 from 3.71 runnin gon CentOS 8 with Java 17 and H2 database.
I am using S3 as my blob store.

During start of nexus 3.74 saw errors which looks like connection issue to S3 storage.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/58a5f272-b1c0-445d-96f5-075e4586ec8f">

Once restarted I went to blob store edit screen and clicked on save and got below error.  

_An error occurred saving data. ERROR: (ID 845202fa-50d7-4ff3-a41f-388dfbc1c64c) java.lang.IllegalArgumentException: Unexpected end of base64-encoded String: base64 variant 'MIME-NO-LINEFEEDS' expects padding (one or more '=' characters) at the end. This Base64Variant might have been incorrectly configured_

<img width="613" alt="image" src="https://github.com/user-attachments/assets/b9a5b347-5cd3-409a-b2bc-456cca855a9c">

I have tried to update the Access Key ID and Access Key Secret but the error is still the same. I verified the Key and Secret, both are correct. 
My S3 blob store does not have any encryption enabled 
<img width="717" alt="image" src="https://github.com/user-attachments/assets/7cea26b5-a73c-48bf-bf8b-ec47637d456e">

**Comment by enys** [comment]
We had a similar issue, inturn in seems to be linked to the fact that Nexus requires new access rights on buckets.
Namely : ObjectStorageBucketPolicyFullAcces

**Comment by enys** [comment]
```



2025-02-03 09:40:34.512 | 2025-02-03 08:40:34,512+0000 ERROR [FelixStartLevel] *SYSTEM org.sonatype.nexus.repository.internal.blobstore.BlobStoreManagerImpl - Unable to start BlobStore lk-prod-nexus-datasets |  
  |   | 2025-02-03 09:40:34.511 | at java.base/java.lang.Thread.run(Thread.java:840) |  
  |   | 2025-02-03 09:40:34.511 | at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) |  
  |   | 2025-02-03 09:40:34.511 | at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1597) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:231) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.extender.NexusContextListener.moveToPhase(NexusContextListener.java:334) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:121) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:210) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:58) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:217) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.doStart(RepositoryManagerImpl.java:235) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:58) |  
  |   | 2025-02-03 09:40:34.511 | at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:217) |  
  |   | 2025-02-03 09:40:34.509 | ... 28 common frames omitted |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.blobstore.s3.internal.S3BlobStore.doInit(S3BlobStore.java:654) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.blobstore.s3.internal.AmazonS3Factory.create(AmazonS3Factory.java:112) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.crypto.secrets.internal.SecretsServiceImpl$SecretImpl.decrypt(SecretsServiceImpl.java:366) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.crypto.secrets.internal.SecretsServiceImpl.doDecrypt(SecretsServiceImpl.java:228) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.crypto.secrets.internal.SecretsServiceImpl.decryptLegacy(SecretsServiceImpl.java:305) |  
  |   | 2025-02-03 09:40:34.509 | at com.fasterxml.jackson.core.Base64Variant.decode(Base64Variant.java:676) |  
  |   | 2025-02-03 09:40:34.509 | at com.fasterxml.jackson.core.Base64Variant.decode(Base64Variant.java:713) |  
  |   | 2025-02-03 09:40:34.509 | at com.fasterxml.jackson.core.Base64Variant._reportInvalidBase64(Base64Variant.java:850) |  
  |   | 2025-02-03 09:40:34.509 | Caused by: java.lang.IllegalArgumentException: Illegal character '-' (code 0x2d) in base64 content |  
  |   | 2025-02-03 09:40:34.509 | at java.base/java.lang.Thread.run(Thread.java:840) |  
  |   | 2025-02-03 09:40:34.509 | at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) |  
  |   | 2025-02-03 09:40:34.509 | at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1597) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:231) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.extender.NexusContextListener.moveToPhase(NexusContextListener.java:334) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:121) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:210) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl$$EnhancerByGuice$$28a1a496.start(<generated>) |  
  |   | 2025-02-03 09:40:34.509 | at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55) |  
  |   | 2025-02-03 09:40:34.509 | at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:58) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:217) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39) |  
  |   | 2025-02-03 09:40:34.509 | at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl$$EnhancerByGuice$$28a1a496.GUICE$TRAMPOLINE(<generated>) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.doStart(RepositoryManagerImpl.java:235) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.repository.internal.blobstore.BlobStoreManagerImpl$$EnhancerByGuice$$2ef58d58.start(<generated>) |  
  |   | 2025-02-03 09:40:34.509 | at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55) |  
  |   | 2025-02-03 09:40:34.509 | at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:58) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:217) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39) |  
  |   | 2025-02-03 09:40:34.509 | at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.repository.internal.blobstore.BlobStoreManagerImpl$$EnhancerByGuice$$2ef58d58.GUICE$TRAMPOLINE(<generated>) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.repository.internal.blobstore.BlobStoreManagerImpl.doStart(BlobStoreManagerImpl.java:179) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.blobstore.BlobStoreSupport.init(BlobStoreSupport.java:280) |  
  |   | 2025-02-03 09:40:34.509 | at org.sonatype.nexus.blobstore.s3.internal.S3BlobStore.doInit(S3BlobStore.java:668) |  
  |   | 2025-02-03 09:40:34.509 | org.sonatype.nexus.blobstore.api.BlobStoreException: Unable to initialize blob store bucket: lk-tf-prod-nexus-docker-dev, Cause: Illegal character '-' (code 0x2d) in base64 content |  
  |  

<br class="Apple-interchange-newline">

```

**Comment by cthu1hoo** [comment]
I managed to upgrade with S3 blobstore from 3.72 to 3.74 and then to 3.79 after doing some very questionable surgery on h2database. I wouldn't recommend doing this in production. :)

I think the underlying issue is that broken S3 blobstore configuration has plaintext password embedded in the attributes JSON value in blob_store_configuration table, while newly created blobstores point a secret in another table somewhere (the syntax is something like "secretAccessKey":"_2" as opposed to "secretAccessKey":"plaintextPass").

1. I've created my-key.json and added it to nexus.properties as documented [here](https://help.sonatype.com/en/re-encryption-in-nexus-repository.html) - I didn't need to manually rotate keys afterwards using the API call;
2. Upgraded to 3.74 and added another S3 blobstore (minio-tmp) in the web UI pointing to a temporary bucket (nexus-tmp) on the same Minio server;
3. Stopped Nexus and ran h2database shell from inside the container while Nexus was not running:

```
$ docker compose run --rm -it nexus java -cp /opt/sonatype/nexus/system/com/h2database/h2/2.2.224/h2-2.2.224.jar org.h2.tools.Shell -url jdbc:h2:/nexus-data/db/nexus
```

After digging around in the database I've noticed that repositories seem to be referring to the blobstore by name, as opposed to some kind of database ID, so I've renamed old minio blobstore to minio-old, renamed minio-tmp to minio, and updated blob store attributes to point to the previously existing bucket with data in it:

```
sql> update blob_store_configuration set name = 'minio-old' where name = 'minio';
(Update count: 1, 5 ms)
sql> update blob_store_configuration set name = 'minio' where name = 'minio-tmp';
(Update count: 1, 0 ms)

sql> update blob_store_configuration set attributes = (select replace(attributes, 'nexus-tmp', 'nexus') format json from blob_store_configuration where name = 'minio') where name = 'minio';
```

Note "format JSON", otherwise attributes content is double-quoted.

Afterwards, I've started Nexus and was able to successfully delete old blobstore with plaintext password, verified several repositories and everything seems to be working properly so far.

Then I've updated from 3.74 to 3.79 with no further issues.

**Comment by wilsoniya** [comment]
I'm experiencing this issue upgrading to `3.82.0-08`. I was able to do the equivalent surgery as @cthu1hoo mentions [above](https://github.com/sonatype/nexus-public/issues/532#issuecomment-2778068647) but would really prefer a proper bugfix!

Thanks!
